// ═══════════════════════════════════════════════════
// 🖼️ Local Images (AUTO-GENERATED — do not edit manually)
// ═══════════════════════════════════════════════════
// Generated by scripts/generate-local-images.ts
// Runs automatically before `npm run dev` and `npm run build`.
//
// To add new images:
//   1. Drop the file in public/images/
//   2. Restart the dev server (or push — Vercel rebuilds automatically)
//
// Do not commit manual changes to this file — they will be overwritten.

export const LOCAL_IMAGES = [
  "/images/basbousaWithCream.jpg",
] as const;

export type LocalImage = (typeof LOCAL_IMAGES)[number];
