// ═══════════════════════════════════════════════════
// 🖼️ Generate Local Images List
// ═══════════════════════════════════════════════════
// Scans public/images/ and writes a typed constant file
// listing every available image path. Runs before `npm run dev`
// and `npm run build`.
//
// Why this exists: the serverless runtime on Vercel cannot
// read the public/ folder at request time — the folder is
// served directly from the CDN. Reading it must happen at
// BUILD time.

import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const IMAGES_DIR = join(process.cwd(), "public", "images");
const OUT_FILE = join(
  process.cwd(),
  "src",
  "lib",
  "constants",
  "local-images.generated.ts"
);

// Only treat these extensions as image files.
const ALLOWED_EXTENSIONS = new Set([
  ".jpg",
  ".jpeg",
  ".png",
  ".webp",
  ".avif",
  ".gif",
  ".svg",
]);

function main() {
  let files: string[] = [];

  if (existsSync(IMAGES_DIR)) {
    files = readdirSync(IMAGES_DIR)
      .filter((name) => {
        const dotIndex = name.lastIndexOf(".");
        if (dotIndex === -1) return false;
        const ext = name.slice(dotIndex).toLowerCase();
        return ALLOWED_EXTENSIONS.has(ext);
      })
      .sort();
  }

  const lines = files.map((name) => `  "/images/${name}",`).join("\n");

  const content = `// ═══════════════════════════════════════════════════
// 🖼️ Local Images (AUTO-GENERATED — do not edit manually)
// ═══════════════════════════════════════════════════
// Generated by scripts/generate-local-images.ts
// Runs automatically before \`npm run dev\` and \`npm run build\`.
//
// To add new images:
//   1. Drop the file in public/images/
//   2. Restart the dev server (or push — Vercel rebuilds automatically)
//
// Do not commit manual changes to this file — they will be overwritten.

export const LOCAL_IMAGES = [
${lines}
] as const;

export type LocalImage = (typeof LOCAL_IMAGES)[number];
`;

  writeFileSync(OUT_FILE, content, "utf8");
  console.log(
    `✅ Generated ${files.length} local image reference(s) → src/lib/constants/local-images.generated.ts`
  );
}

main();